version: 2

build:
  os: windows
  tools:
    dotnet: 8.0

sphinx:
  configuration: docs/conf.py

python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt

formats:
  - pdf
  - epub
